# Generated by Django 3.1.2 on 2020-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pp',
            field=models.ImageField(default='default/default.jpg', upload_to='profile_pics'),
        ),
    ]
