# Generated by Django 3.1.2 on 2020-10-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201013_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pp',
            field=models.ImageField(default='default/default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
