# Generated by Django 3.1.2 on 2020-10-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201013_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
    ]
